# Generated by Django 4.1.6 on 2023-02-09 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField(default='1999-11-10')),
                ('comorbidities', models.BooleanField(default=False)),
                ('allergies', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_name'],
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(choices=[('6 mos to 4 years', '6 mos to 4 years'), ('6 mos to 5 years', '6 mos to 5 years'), ('age 5-11', 'age 5-11'), ('age 6-11', 'age 6-11'), ('12 and older', '12 and older'), ('18 and older', '18 and older')], default='12 and older', max_length=255)),
                ('cap_color', models.CharField(default='gray', max_length=50)),
                ('border_color', models.CharField(default='gray', max_length=50)),
                ('dose', models.CharField(default='-', max_length=50)),
                ('doses_per_vial', models.IntegerField(default=6)),
                ('dilution', models.BooleanField(default=True)),
                ('storage', models.CharField(default='-', max_length=255)),
                ('thaw', models.CharField(default='-', max_length=255)),
                ('bud', models.CharField(default='6 hours after puncture', max_length=50)),
                ('ndc', models.CharField(default='-', max_length=50)),
                ('link', models.CharField(default='-', max_length=255)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='VaccineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_administered', models.DateField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
                ('vaccine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vaccine')),
            ],
        ),
    ]
